# Generated by Django 2.2.7 on 2020-05-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubKey',
        ),
    ]
