# Generated by Django 2.2.4 on 2021-02-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address_category_item_location_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='location',
        ),
    ]
