# Generated by Django 2.2.4 on 2021-02-12 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Category')),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SubCategory')),
            ],
        ),
    ]
